version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - 8080:8080
    env_file:
      - ./.env.dev
    entrypoint: pytest
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
volumes:
  postgres_data: